name: vqa_score_predictions

run:
  name: actual_run
  output_root: ${project.root_dir}/results
  prediction_filename: predictions.parquet
  metrics_filename: metrics.json

metrics:
  bert_score:
    enabled: true
    model_type: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext
    num_layers: 9
    lang: en
    batch_size: 8
    max_length: 512
    rescale_with_baseline: false
    use_fast_tokenizer: true
