instantiate_model: false
always_frozen_prefixes:
  - pathology
  - radiology
  - segmentation
projector_prefixes:
  - projector
  - projectors
batch_size: 4
num_epochs: 1
learning_rate: 1e-3
output_dir: ${project.root_dir}/outputs/train/projectors
