defaults:
  - data: global
  - 01_pathology_features@pathology_features: default
  - 01_pathology_segmentation@pathology_segmentation: 01_run_pathology_segmentation
  - 01_pathology_proj@pathology_proj: 04_train_path_projectors
  - 02_radiology_proj@radiology_proj: 03_train_radiology_projectors
  - 03_dnam_proj@dnam_proj: 04_train_dnam_projectors
  - demo: demo_path_projector
  - vlm_train: medgemma_hf
  - _self_

project:
  name: kidney-vlm
  root_dir: ${oc.env:KIDNEY_VLM_ROOT}
