defaults:
  - data: global
  - qa_genereation: qa
  - embeding_extraction/pathology: trident
  - embeding_extraction/radiology: foundation_placeholder
  - embeding_extraction/segmentation: pathology_placeholder
  - path_proj_train: default
  - rad_proj_train: default
  - demo: demo_path_projector
  - vlm_train: medgemma_hf
  - _self_

project:
  name: kidney-vlm
  root_dir: ${oc.env:KIDNEY_VLM_ROOT}
